export const GET_HAPPY_REQUEST = "GET_HAPPY_REQUEST";
export const GET_HAPPY_SUCCESS = "GET_HAPPY_SUCCESS";
export const GET_HAPPY_FAILURE = "GET_HAPPY_FAILURE";
export const GET_HAPPY_RESET = "GET_HAPPY_RESET";

export const GET_ANGRY_REQUEST = "GET_ANGRY_REQUEST";
export const GET_ANGRY_SUCCESS = "GET_ANGRY_SUCCESS";
export const GET_ANGRY_FAILURE = "GET_ANGRY_FAILURE";
export const GET_ANGRY_RESET = "GET_ANGRY_RESET";
