# Generated by Django 2.0.7 on 2018-07-20 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('xxl', models.BooleanField()),
                ('description', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cloth_type', models.CharField(choices=[('GE', 'General'), ('SH', 'Short'), ('TE', 'T-Shirt'), ('PA', 'Pants'), ('SO', 'Socks'), ('UN', 'Underwear'), ('HO', 'Shoes'), ('SR', 'Shirts')], default='GE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.IntegerField()),
                ('long', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cloth',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroapiapp.Shop'),
        ),
    ]
