# Generated by Django 2.0.7 on 2018-07-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroapiapp', '0002_auto_20180720_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='image',
            field=models.ImageField(upload_to='cloth_images/'),
        ),
    ]
