# Generated by Django 2.0.7 on 2018-07-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroapiapp', '0003_auto_20180721_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='description',
        ),
    ]
