# Generated by Django 2.0.7 on 2018-07-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroapiapp', '0005_auto_20180721_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('sound', models.FileField(upload_to='sounds/')),
            ],
        ),
    ]
