# Generated by Django 2.0.7 on 2018-07-21 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroapiapp', '0006_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='heroapiapp.Shop'),
        ),
    ]
