# Generated by Django 2.0.7 on 2018-07-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroapiapp', '0007_auto_20180721_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='happy',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
